import React, { useState } from 'react';
import { ShieldCheck, Loader2, CheckCircle2, AlertCircle } from 'lucide-react';
import { KawacanaanEmblem } from '../components/KawacanaanEmblem';

export const SetupSuperAdminView: React.FC = () => {
  const [name,setName]=useState(''); const [username,setUsername]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [secret,setSecret]=useState('');
  const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [success,setSuccess]=useState('');
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setError('');setSuccess('');setLoading(true);try{const r=await fetch('/api/setup-superadmin',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name,username,email,password,setupSecret:secret})});const b=await r.json();if(!r.ok)throw new Error(b.error||'Setup gagal.');setSuccess(b.message||'Super Admin berhasil dibuat.');setPassword('');}catch(e:any){setError(e.message||'Setup gagal.');}finally{setLoading(false);}};
  return <div className="min-h-screen bg-slate-950 flex items-center justify-center p-5"><div className="w-full max-w-lg bg-white rounded-3xl p-7 sm:p-9 shadow-2xl"><div className="flex flex-col items-center text-center"><KawacanaanEmblem size={68}/><h1 className="mt-4 text-2xl font-black text-slate-900">Setup Super Admin</h1><p className="mt-2 text-sm text-slate-500">Halaman ini hanya untuk pembuatan SUPER ADMIN pertama. Setelah berhasil, endpoint setup otomatis terkunci.</p></div>{error&&<div className="mt-5 p-3 rounded-2xl bg-rose-50 border border-rose-200 text-rose-700 text-xs flex gap-2"><AlertCircle size={16}/><span>{error}</span></div>}{success&&<div className="mt-5 p-3 rounded-2xl bg-emerald-50 border border-emerald-200 text-emerald-700 text-xs flex gap-2"><CheckCircle2 size={16}/><span>{success}</span></div>}<form onSubmit={submit} className="mt-6 space-y-3.5"><input required value={name} onChange={e=>setName(e.target.value)} placeholder="Nama Super Admin" className="w-full px-4 py-3 rounded-2xl border border-slate-200 bg-slate-50"/><input required value={username} onChange={e=>setUsername(e.target.value.toLowerCase())} placeholder="Username" className="w-full px-4 py-3 rounded-2xl border border-slate-200 bg-slate-50"/><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email Google (disarankan)" className="w-full px-4 py-3 rounded-2xl border border-slate-200 bg-slate-50"/><input required minLength={12} type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password minimal 12 karakter" className="w-full px-4 py-3 rounded-2xl border border-slate-200 bg-slate-50"/><input required type="password" value={secret} onChange={e=>setSecret(e.target.value)} placeholder="SUPERADMIN_SETUP_SECRET dari Vercel" className="w-full px-4 py-3 rounded-2xl border border-slate-200 bg-slate-50"/><button disabled={loading} className="w-full py-3.5 rounded-2xl bg-indigo-600 text-white font-bold flex items-center justify-center gap-2 disabled:opacity-60">{loading?<Loader2 size={18} className="animate-spin"/>:<ShieldCheck size={18}/>} Buat Super Admin Pertama</button></form><p className="mt-5 text-[11px] text-slate-400 text-center">Jangan bagikan Setup Secret. Password disimpan hanya oleh Supabase Auth.</p></div></div>;
};
